/**
 * Information architecture of the component reference. Every example must be
 * listed exactly once — in a category, or as a part of its parent — and
 * `scripts/gen-ui-docs.ts` fails otherwise.
 */

export type Category = { id: string; label: string; components: string[] };

export const categories: Category[] = [
	{
		id: "buttons",
		label: "Buttons & actions",
		components: [
			"Button",
			"UnstyledButton",
			"ButtonGroup",
			"SplitButton",
			"ToggleGroup",
			"Segmented",
			"ActionIcon",
			"CloseButton",
			"Burger",
			"FloatingActionButton",
			"LoadingButton",
			"ConfirmButton",
			"CopyButton",
			"CopyId",
			"ShareButton",
			"ViewToggle",
			"DensityToggle",
			"ThemeToggle",
			"CommandBar",
			"FloatingToolbar",
			"BulkBar",
		],
	},
	{
		id: "inputs",
		label: "Inputs",
		components: [
			"TextInput",
			"TextArea",
			"NumberInput",
			"PasswordInput",
			"PasswordStrength",
			"SearchInput",
			"PinInput",
			"InputGroup",
			"Checkbox",
			"CheckboxGroup",
			"Checklist",
			"Switch",
			"RadioGroup",
			"ChoiceCard",
			"Select",
			"NativeSelect",
			"MultiSelect",
			"Autocomplete",
			"TagsInput",
			"ChipGroup",
			"Chip",
			"Rating",
			"Slider",
			"RangeSlider",
			"AngleSlider",
			"QuantityInput",
			"InlineEdit",
			"SecretField",
			"CopyField",
			"JsonInput",
			"FileInput",
			"FileButton",
			"Dropzone",
			"UploadItem",
		],
	},
	{
		id: "pickers",
		label: "Date & colour pickers",
		components: [
			"DateInput",
			"TimeInput",
			"Calendar",
			"DatePicker",
			"DateRangePicker",
			"MonthPicker",
			"YearPicker",
			"TimePicker",
			"ColorInput",
			"ColorPicker",
			"ColorSwatch",
		],
	},
	{
		id: "forms",
		label: "Form layout",
		components: [
			"FormField",
			"Label",
			"Fieldset",
			"FormSection",
			"FormArea",
			"FormFooter",
			"SettingsRow",
			"ToggleRow",
			"DangerZone",
			"WizardNav",
		],
	},
	{
		id: "overlays",
		label: "Overlays",
		components: [
			"Modal",
			"Drawer",
			"BottomSheet",
			"ConfirmDialog",
			"Popover",
			"HoverCard",
			"Tooltip",
			"Menu",
			"ContextMenu",
			"Spotlight",
			"Lightbox",
			"Overlay",
			"LoadingOverlay",
		],
	},
	{
		id: "navigation",
		label: "Navigation",
		components: [
			"Navbar",
			"AppShell",
			"SidebarNav",
			"Breadcrumb",
			"Tabs",
			"Steps",
			"Pagination",
			"DotPagination",
			"NextPrev",
			"BackLink",
			"Subnav",
			"Iconnav",
			"NavLink",
			"Anchor",
			"TableOfContents",
			"ScrollSpy",
			"SkipLink",
			"BottomNav",
			"Thumbnav",
			"ToTop",
			"Affix",
			"Sticky",
			"StickyBar",
			"UserButton",
			"LocaleSwitcher",
			"OrgSwitcher",
		],
	},
	{
		id: "feedback",
		label: "Feedback & status",
		components: [
			"Alert",
			"Callout",
			"Message",
			"Notification",
			"ToastHost",
			"Banner",
			"AnnouncementBar",
			"UpgradeBanner",
			"CookieConsent",
			"OfflineNotice",
			"Spinner",
			"Progress",
			"SteppedProgress",
			"NavigationProgress",
			"RingProgress",
			"SemiCircleProgress",
			"Meter",
			"Gauge",
			"UsageMeter",
			"StorageBar",
			"Skeleton",
			"SkeletonText",
			"SkeletonCard",
			"EmptyState",
			"NoResults",
			"ErrorState",
			"StatusDot",
			"Indicator",
			"LiveBadge",
			"UnreadBadge",
			"TypingIndicator",
			"SyncStatus",
			"AutosaveIndicator",
			"LastSaved",
			"Countdown",
		],
	},
	{
		id: "data",
		label: "Data display",
		components: [
			"Table",
			"DataTable",
			"DescriptionList",
			"PropertyList",
			"List",
			"ListGroup",
			"Timeline",
			"Accordion",
			"Collapse",
			"Spoiler",
			"Details",
			"Tree",
			"FileTree",
			"JsonTree",
			"JsonViewer",
			"TransferList",
			"SortableList",
			"KanbanBoard",
			"Carousel",
			"Badge",
			"Tag",
			"FilterChip",
			"Avatar",
			"AvatarGroup",
			"PresenceAvatar",
			"Kbd",
			"Hotkey",
			"Code",
			"CodeBlock",
			"Diff",
			"Terminal",
			"LogViewer",
			"Mark",
			"Highlight",
			"Truncate",
			"Leader",
			"NumberFormatter",
			"RelativeTime",
			"Price",
			"ResultCount",
			"LoadMore",
			"InfiniteScroll",
		],
	},
	{
		id: "charts",
		label: "Stats & charts",
		components: [
			"Stat",
			"StatCard",
			"Metric",
			"Trend",
			"CountUp",
			"Sparkline",
			"SparkBar",
			"BarList",
			"DonutChart",
			"Heatmap",
			"UptimeBar",
		],
	},
	{
		id: "layout",
		label: "Layout",
		components: [
			"Stack",
			"Group",
			"Flex",
			"Center",
			"Space",
			"Box",
			"Paper",
			"Block",
			"Tile",
			"Card",
			"Panel",
			"Inset",
			"Bleed",
			"Columns",
			"Grid",
			"Container",
			"Section",
			"Level",
			"Hero",
			"Media",
			"Footer",
			"SiteFooter",
			"Divider",
			"AspectRatio",
			"ScrollArea",
			"Splitter",
			"Masonry",
			"Reel",
			"GalleryGrid",
			"FilterBar",
		],
	},
	{
		id: "content",
		label: "Typography & content",
		components: [
			"Text",
			"Title",
			"Subtitle",
			"Heading",
			"Prose",
			"Quote",
			"Article",
			"PageHeader",
			"Figure",
			"Image",
			"BackgroundImage",
			"VideoFrame",
			"BeforeAfter",
			"Marquee",
			"Icon",
			"IconBadge",
			"VisuallyHidden",
			"Mention",
			"Comment",
			"ChatBubble",
			"ActivityItem",
			"InboxItem",
			"ReactionBar",
			"Testimonial",
			"ReviewCard",
			"LogoCloud",
			"BrowserFrame",
			"PhoneFrame",
			"SocialLinks",
		],
	},
	{
		id: "commerce",
		label: "Commerce & billing",
		components: [
			"ProductCard",
			"CartLine",
			"OrderSummary",
			"PricingCard",
			"FeatureList",
			"FeatureCompare",
			"CreditCardPreview",
			"InvoiceRow",
		],
	},
	{
		id: "developer",
		label: "Developer & ops",
		components: [
			"ChangelogItem",
			"VersionTag",
			"EnvBadge",
			"HttpMethodBadge",
			"EndpointRow",
			"ServiceStatus",
			"BuildStatus",
			"Pipeline",
			"CommitChip",
			"BranchBadge",
			"ProfileHeader",
			"MemberRow",
			"RoleBadge",
			"InviteCard",
			"PriorityBadge",
			"SeverityBadge",
			"FileCard",
		],
	},
	{
		id: "docs",
		label: "Documentation",
		components: ["DocPage", "DocExample", "DocMenu"],
	},
];

/** Sub-components documented on their parent's page (as "Parts"). */
export const parts: Record<string, string[]> = {
	Card: [
		"CardHeader",
		"CardHeaderTitle",
		"CardImage",
		"CardContent",
		"CardFooter",
		"CardFooterItem",
	],
	Panel: ["PanelHeading", "PanelTabs", "PanelTab", "PanelBlock"],
	Message: ["MessageHeader", "MessageBody"],
	Hero: ["HeroHead", "HeroBody", "HeroFoot"],
	Media: ["MediaLeft", "MediaContent", "MediaRight"],
	Article: ["ArticleTitle", "ArticleMeta"],
	Columns: ["Column"],
	Grid: ["GridItem"],
	Level: ["LevelLeft", "LevelRight", "LevelItem"],
	Table: ["Thead", "Tbody", "Tfoot", "Tr", "Th", "Td"],
	List: ["ListItem"],
	ListGroup: ["ListGroupItem"],
	Timeline: ["TimelineItem"],
	KanbanBoard: ["KanbanColumn", "KanbanCard"],
	Navbar: ["NavbarLink"],
	Tag: ["Tags"],
	Stat: ["StatGroup"],
	InputGroup: ["InputAddon"],
	FormField: ["Control", "Help"],
};

/**
 * Components that already have a hand-written showcase page (playground page id
 * → component). Their reference is appended there instead of a catalog entry.
 */
export const curatedPages: Record<string, string> = {
	button: "Button",
	box: "Box",
	tag: "Tag",
	badge: "Badge",
	progress: "Progress",
	notification: "Notification",
	icon: "Icon",
	title: "Title",
	table: "Table",
	image: "Image",
	breadcrumb: "Breadcrumb",
	card: "Card",
	dropdown: "Drawer",
	menu: "Menu",
	message: "Message",
	modal: "Modal",
	navbar: "Navbar",
	pagination: "Pagination",
	panel: "Panel",
	tabs: "Tabs",
	input: "TextInput",
	textarea: "TextArea",
	select: "Select",
	checkbox: "Checkbox",
	radio: "RadioGroup",
	switch: "Switch",
	columns: "Columns",
	container: "Container",
	hero: "Hero",
	level: "Level",
	section: "Section",
};
