import { existsSync, readFileSync } from "node:fs";
import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { bunPlugin } from "@arachne/vite";
import { buildClient, buildSsr } from "./bundle.ts";
import { type KitConfig, type ResolvedConfig, resolveConfig } from "./config.ts";
import { writeEntries } from "./entries.ts";
import { type PrerenderResult, prerender } from "./prerender.ts";
import { loadServer } from "./server-def.ts";

/** Options for {@link build}: config overrides. */
export type BuildOptions = KitConfig;

/** Output of {@link build}. */
export interface BuildResult {
	/** Build mode used. */
	mode: ResolvedConfig["mode"];
	/** Output directory. */
	outDir: string;
	/** Prerendered pages (static mode). */
	pages: PrerenderResult["pages"];
	/** Dynamic routes skipped for lack of `paths` (static mode). */
	skipped: string[];
	/** The server bundle to run with `bun` (server and API modes). */
	serverEntry: string | undefined;
}

function importPath(from: string, to: string): string {
	const path = relative(from, to).split("\\").join("/");
	return path.startsWith(".") ? path : `./${path}`;
}

/** Direct, non-Arachne dependencies of the app: left external in the server bundle. */
function externalDependencies(root: string): string[] {
	const file = join(root, "package.json");
	if (!existsSync(file)) return [];
	const pkg = JSON.parse(readFileSync(file, "utf8")) as { dependencies?: Record<string, string> };
	return Object.keys(pkg.dependencies ?? {})
		.filter((name) => !name.startsWith("@arachne/"))
		.flatMap((name) => [name, `${name}/*`]);
}

function serverEntrySource(config: ResolvedConfig, ssrFile: string | undefined): string {
	const dir = config.cacheDir;
	const configFile = ["arachne.config.ts", "arachne.config.js"]
		.map((f) => join(config.root, f))
		.find(existsSync);
	return `// Generated by @arachne/kit. Do not edit.
import { join } from "node:path";
import { createProductionServer } from "@arachne/kit";
${configFile ? `import config from ${JSON.stringify(importPath(dir, configFile))};` : "const config = {};"}
${ssrFile ? `import * as ssr from ${JSON.stringify(importPath(dir, ssrFile))};` : "const ssr = undefined;"}
${config.serverFile ? `import server from ${JSON.stringify(importPath(dir, config.serverFile))};` : "const server = {};"}

const clientDir = join(import.meta.dir, "../client");
const manifest = await Bun.file(join(clientDir, ".arachne-manifest.json")).json();
const app = await createProductionServer({ config, clientDir, manifest, ssr, server });
const { url } = app.listen();
console.log(\`arachne: listening on \${url}\`);
for (const signal of ["SIGINT", "SIGTERM"]) process.on(signal, () => app.close().then(() => process.exit(0)));
`;
}

async function buildServerBundle(config: ResolvedConfig, outDir: string): Promise<string> {
	const { ssr } = config.routesFile ? await writeEntries(config) : { ssr: undefined };
	const entry = join(config.cacheDir, "server-entry.ts");
	await mkdir(config.cacheDir, { recursive: true });
	await writeFile(entry, serverEntrySource(config, ssr));
	const result = await Bun.build({
		entrypoints: [entry],
		root: config.root,
		outdir: join(outDir, "server"),
		naming: "index.[ext]",
		target: "bun",
		format: "esm",
		minify: { syntax: true, whitespace: true, identifiers: false },
		sourcemap: "linked",
		plugins: [bunPlugin({ target: "ssr", hydratable: true })],
		external: externalDependencies(config.root),
	});
	if (!result.success)
		throw new Error(`server build failed:\n${result.logs.map(String).join("\n")}`);
	return join(outDir, "server", "index.js");
}

/**
 * Production build.
 * - `static`: prerendered HTML, `_data/*.json`, assets, public files → `outDir`
 * - `server` / `api`: `outDir/client` (assets + public) and `outDir/server/index.js`
 */
export async function build(root: string, options: BuildOptions = {}): Promise<BuildResult> {
	const config = await resolveConfig(root, options);
	const client = await buildClient(config, { dev: false });
	if (config.mode === "static") {
		if (!config.routesFile) throw new Error("static builds need app/routes.tsx");
		const ssr = await buildSsr(config, { dev: false });
		const server = await loadServer(config, false);
		try {
			const result = await prerender(config, ssr.module, server, client, config.outDir);
			return {
				mode: config.mode,
				outDir: config.outDir,
				pages: result.pages,
				skipped: result.skipped,
				serverEntry: undefined,
			};
		} finally {
			await server.dispose?.();
			await rm(join(config.cacheDir, "ssr"), { recursive: true, force: true });
		}
	}
	await rm(config.outDir, { recursive: true, force: true });
	const clientDir = join(config.outDir, "client");
	await mkdir(clientDir, { recursive: true });
	if (existsSync(config.publicDir)) await cp(config.publicDir, clientDir, { recursive: true });
	for (const [url, asset] of client.files) {
		const file = join(clientDir, url.slice(config.base.length));
		await mkdir(join(file, ".."), { recursive: true });
		await writeFile(file, asset.bytes);
	}
	await writeFile(
		join(clientDir, ".arachne-manifest.json"),
		JSON.stringify({ entry: client.entry, styles: client.styles }),
	);
	const serverEntry = await buildServerBundle(config, config.outDir);
	return { mode: config.mode, outDir: config.outDir, pages: [], skipped: [], serverEntry };
}
