import { mkdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import type { ResolvedConfig } from "./config.ts";

/** Events the client delegates to the root (matches what `@arachne/ui` needs). */
const DELEGATED_EVENTS = [
	"click",
	"input",
	"change",
	"keydown",
	"keyup",
	"submit",
	"focusin",
	"focusout",
	"pointerdown",
	"pointerup",
	"pointermove",
	"contextmenu",
];

function importPath(from: string, to: string): string {
	const path = relative(from, to).split("\\").join("/");
	return path.startsWith(".") ? path : `./${path}`;
}

/** Source of the generated browser entry (`.arachne/client.tsx`). */
export function clientEntrySource(config: ResolvedConfig): string {
	const routes = importPath(config.cacheDir, config.routesFile ?? "");
	return `// Generated by @arachne/kit. Do not edit.
import { delegateEvents, hydrate } from "@arachne/render";
import { browserHistory, createRouter } from "@arachne/router";
import * as app from ${JSON.stringify(routes)};

const boot = JSON.parse(document.getElementById("__arachne")?.textContent ?? "{}");
const base = boot.base === "/" ? "" : String(boot.base ?? "").replace(/\\/$/, "");
const loaders = new Set(boot.loaders ?? []);

async function load(match) {
	if (!loaders.has(match.id)) return undefined;
	const path = match.pathname === "/" ? "/index" : match.pathname;
	const url = boot.mode === "static" ? \`\${base}/_data\${path}.json\` : \`\${base}/__arachne/data\${match.pathname}\${match.search}\`;
	const response = await fetch(url, { headers: { accept: "application/json" } });
	const body = await response.json().catch(() => ({}));
	if (!response.ok) throw Object.assign(new Error(body?.error?.message ?? \`HTTP \${response.status}\`), { status: response.status });
	return body.data;
}

const router = createRouter({
	routes: app.routes ?? app.default,
	history: browserHistory(),
	base,
	titleTemplate: boot.titleTemplate,
	initialData: boot.data ?? null,
	initialError: boot.error,
	load,
	fallback: app.NotFound,
	error: app.ErrorPage,
});
delegateEvents(${JSON.stringify(DELEGATED_EVENTS)});
await router.ready;
const root = document.getElementById("app");
if (root) hydrate(() => router.Outlet(), root);
router.interceptLinks();
`;
}

/** Source of the generated SSR module (`.arachne/ssr.tsx`). */
export function ssrEntrySource(config: ResolvedConfig): string {
	const routes = importPath(config.cacheDir, config.routesFile ?? "");
	return `// Generated by @arachne/kit. Do not edit.
import { renderToString } from "@arachne/render/ssr";
import { compilePath, createRouter, listRoutes, memoryHistory, renderHead, withRouter } from "@arachne/router";
import * as app from ${JSON.stringify(routes)};

const routes = app.routes ?? app.default ?? [];
const DefaultError = () => "Something went wrong";

/** Every page route: id, pattern and whether it needs params. */
export function routeList() {
	return listRoutes(routes);
}

/** Build a URL for a pattern and params. */
export function buildPath(pattern, params) {
	return compilePath(pattern).build(params);
}

/** Match a URL (app path, base removed) to a route. */
export function match(url) {
	const router = createRouter({ routes, history: memoryHistory(url) });
	const m = router.matched();
	router.dispose();
	return m ? { id: m.id, pattern: m.pattern, params: m.params } : null;
}

/** Render a URL (app path, base removed) with a loader. */
export async function render(url, options) {
	const router = createRouter({
		routes,
		history: memoryHistory(url),
		load: options.load,
		titleTemplate: options.titleTemplate,
		base: options.base,
		fallback: app.NotFound,
		error: app.ErrorPage ?? DefaultError,
	});
	await router.ready;
	const html = withRouter(router, () => renderToString(() => router.Outlet()));
	const matched = router.matched();
	const error = router.error();
	const head = router.head();
	if (head.title === undefined && options.defaultTitle) head.title = options.defaultTitle;
	router.dispose();
	return {
		html,
		head: renderHead(head),
		title: head.title,
		data: router.data(),
		routeId: matched?.id ?? null,
		matched: matched !== null,
		error,
	};
}
`;
}

/** Write the generated entries into the cache directory and return their paths. */
export async function writeEntries(
	config: ResolvedConfig,
): Promise<{ client: string; ssr: string }> {
	await mkdir(config.cacheDir, { recursive: true });
	const client = join(config.cacheDir, "client.tsx");
	const ssr = join(config.cacheDir, "ssr.tsx");
	await writeFile(client, clientEntrySource(config));
	await writeFile(ssr, ssrEntrySource(config));
	return { client, ssr };
}
