import { type AnySchema, parse, s, safeParse } from "@arachne/schema";

/** Storage class of a column. */
export type SqlType = "text" | "integer" | "real" | "boolean" | "json" | "date";

/** What happens to referencing rows when the referenced row goes away. */
export type ReferentialAction = "cascade" | "restrict" | "set null" | "no action";

/** Foreign key target. */
export interface ColumnReference {
	/** Referenced table name. */
	table: string;
	/** Referenced column. Default `id`. */
	column?: string;
	/** `ON DELETE` action. */
	onDelete?: ReferentialAction;
	/** `ON UPDATE` action. */
	onUpdate?: ReferentialAction;
}

/** Column options. Nullability comes from the schema (`s.nullable(...)`). */
export interface ColumnOptions {
	/** Primary key (implies not null). */
	primaryKey?: boolean | undefined;
	/** Integer key generated by the database (SQLite `AUTOINCREMENT`). */
	autoIncrement?: boolean | undefined;
	/** Force `NOT NULL` even if the schema accepts `null`. */
	notNull?: boolean | undefined;
	/** Unique constraint. */
	unique?: boolean | undefined;
	/** Value used when an insert omits the column (called per insert). */
	default?: (() => unknown) | undefined;
	/** Foreign key. */
	references?: ColumnReference | undefined;
}

/**
 * A column: storage type, validating schema and constraints.
 *
 * @typeParam TSchema - schema for the column's values
 * @typeParam TOptional - whether inserts may omit it (default or auto-increment)
 */
export interface ColumnDef<
	TSchema extends AnySchema = AnySchema,
	TOptional extends boolean = boolean,
> {
	/** Storage class. */
	readonly sqlType: SqlType;
	/** Validates values on insert/update and rows on read. */
	readonly schema: TSchema;
	/** Primary key. */
	readonly primaryKey: boolean;
	/** Database-generated integer key. */
	readonly autoIncrement: boolean;
	/** `NOT NULL`. */
	readonly notNull: boolean;
	/** `UNIQUE`. */
	readonly unique: boolean;
	/** Insert default. */
	readonly default: (() => unknown) | undefined;
	/** Foreign key. */
	readonly references: ColumnReference | undefined;
	/** Phantom: inserts may omit this column. */
	readonly "~optional"?: TOptional;
}

type OptionalFlag<O> = O extends { default: () => unknown } | { autoIncrement: true }
	? true
	: false;

type SchemaOf<T> = AnySchema & { readonly _output: T };

function column<TSchema extends AnySchema, O extends ColumnOptions>(
	sqlType: SqlType,
	schema: TSchema,
	options: O | undefined,
): ColumnDef<TSchema, OptionalFlag<O>> {
	const opts: ColumnOptions = options ?? {};
	const acceptsNull = !safeParse(schema, null).issues;
	return {
		sqlType,
		schema,
		primaryKey: opts.primaryKey ?? false,
		autoIncrement: opts.autoIncrement ?? false,
		notNull: opts.notNull ?? (opts.primaryKey || !acceptsNull),
		unique: opts.unique ?? false,
		default: opts.default,
		references: opts.references,
	};
}

/**
 * Column builders. Each pairs a storage class with a schema; `json` stores
 * any schema as JSON text and `date` stores `Date`s as epoch milliseconds.
 *
 * @example
 * ```ts
 * const users = defineTable("users", {
 *   id: col.text(s.uuid(), { primaryKey: true, default: () => crypto.randomUUID() }),
 *   email: col.text(s.email(), { unique: true }),
 *   deletedAt: col.date({ schema: s.nullable(s.date()) }),
 * });
 * ```
 */
export const col = {
	/** `TEXT`. */
	text: <S extends SchemaOf<string | null>, const O extends ColumnOptions = Record<never, never>>(
		schema: S,
		options?: O,
	) => column("text", schema, options),
	/** `INTEGER`. */
	integer: <
		S extends SchemaOf<number | null>,
		const O extends ColumnOptions = Record<never, never>,
	>(
		schema: S,
		options?: O,
	) => column("integer", schema, options),
	/** `REAL`. */
	real: <S extends SchemaOf<number | null>, const O extends ColumnOptions = Record<never, never>>(
		schema: S,
		options?: O,
	) => column("real", schema, options),
	/** Stored as `0`/`1`. */
	boolean: <
		S extends SchemaOf<boolean | null>,
		const O extends ColumnOptions = Record<never, never>,
	>(
		schema: S,
		options?: O,
	) => column("boolean", schema, options),
	/** Any JSON-serialisable value, validated by `schema`. */
	json: <S extends AnySchema, const O extends ColumnOptions = Record<never, never>>(
		schema: S,
		options?: O,
	) => column("json", schema, options),
	/** `Date` stored as epoch ms. Pass `schema: s.nullable(s.date())` for nullable dates. */
	date: <const O extends ColumnOptions & { schema?: SchemaOf<Date | null> } = Record<never, never>>(
		options?: O,
	): ColumnDef<
		O extends { schema: infer S extends AnySchema } ? S : ReturnType<typeof s.date>,
		OptionalFlag<O>
	> => column("date", (options?.schema ?? s.date()) as never, options) as never,
};

/** Column map of a table. */
export type ColumnMap = Record<string, ColumnDef>;

/** Secondary index. */
export interface IndexDef {
	/** Indexed columns, in order. */
	columns: readonly string[];
	/** Unique index. */
	unique?: boolean;
	/** Index name. Default `<table>_<columns>_idx`. */
	name?: string;
}

/** Table options. */
export interface TableOptions {
	/** Secondary indexes created by `sync()`. */
	indexes?: readonly IndexDef[];
}

/** A table definition. */
export interface TableDef<TColumns extends ColumnMap = ColumnMap> {
	/** Table name. */
	readonly name: string;
	/** Columns by name. */
	readonly columns: TColumns;
	/** Secondary indexes. */
	readonly indexes: readonly IndexDef[];
}

type Simplify<T> = { [K in keyof T]: T[K] } & {};

/** A row as read from the table. */
export type InferRow<TColumns extends ColumnMap> = Simplify<{
	[K in keyof TColumns]: TColumns[K]["schema"]["_output"];
}>;

type InsertOptionalKeys<C extends ColumnMap> = {
	[K in keyof C]: Exclude<C[K]["~optional"], undefined> extends true
		? K
		: undefined extends C[K]["schema"]["_input"]
			? K
			: never;
}[keyof C];

/** A row as accepted by `insert`: columns with defaults or auto-increment are optional. */
export type InferInsert<TColumns extends ColumnMap> = Simplify<
	{
		[K in Exclude<keyof TColumns, InsertOptionalKeys<TColumns>>]: TColumns[K]["schema"]["_input"];
	} & {
		[K in InsertOptionalKeys<TColumns>]?: TColumns[K]["schema"]["_input"];
	}
>;

/** Define a table. Names must be non-empty; `sync()` creates it. */
export function defineTable<TColumns extends ColumnMap>(
	name: string,
	columns: TColumns,
	options: TableOptions = {},
): TableDef<TColumns> {
	if (!name) throw new Error("table name is required");
	for (const index of options.indexes ?? []) {
		for (const column of index.columns) {
			if (!(column in columns)) throw new Error(`index on ${name}: unknown column "${column}"`);
		}
	}
	return { name, columns, indexes: options.indexes ?? [] };
}

/** Validate one value with a column's schema. */
export function parseColumn(table: TableDef, key: string, value: unknown): unknown {
	const column = table.columns[key];
	if (!column) throw new Error(`unknown column "${key}" on ${table.name}`);
	try {
		return parse(column.schema, value);
	} catch (error) {
		throw new Error(`${table.name}.${key}: ${(error as Error).message}`, { cause: error });
	}
}

/** Validate a full row against the table's column schemas. */
export function parseRow<TColumns extends ColumnMap>(
	table: TableDef<TColumns>,
	value: unknown,
): InferRow<TColumns> {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		throw new Error(`expected object for table ${table.name}`);
	}
	const input = value as Record<string, unknown>;
	const out: Record<string, unknown> = {};
	for (const key of Object.keys(table.columns)) out[key] = parseColumn(table, key, input[key]);
	return out as InferRow<TColumns>;
}

/** JS value → database value for a column (booleans, JSON, dates). */
export function encodeValue(column: ColumnDef, value: unknown): unknown {
	if (value === null || value === undefined) return null;
	switch (column.sqlType) {
		case "boolean":
			return value ? 1 : 0;
		case "json":
			return JSON.stringify(value);
		case "date":
			return value instanceof Date ? value.getTime() : value;
		default:
			return value;
	}
}

/** Database value → JS value for a column. */
export function decodeValue(column: ColumnDef, value: unknown): unknown {
	if (value === null || value === undefined) return null;
	switch (column.sqlType) {
		case "boolean":
			return Boolean(value);
		case "json":
			return typeof value === "string" ? JSON.parse(value) : value;
		case "date":
			return new Date(Number(value));
		default:
			return value;
	}
}
